### PR TITLE
Added serbian language

### PR DESCRIPTION
**Pull request by mika76**

### CODE REVIEW

**Comment by titoBouzout** [comment]
Thanks a lot ~.-

**Comment by mika76** [comment]
No prob :) when do you update the sublime package?

**Comment by mika76** [comment]
Oh wow done already I see - brilliant thanks.

**Comment by titoBouzout** [comment]
Yes, package are created automatically from the version of github unless they have some special file telling package control what to do (if update from a branch or something) 

=)

**Comment by mika76** [comment]
Sweet - already working. I only find out now that you can only run one dictionary at a time in Sublime text - oh well at least it's quick to change using the package ;)

**Pull request merged**
